name: Austin Hackers Anonymous
url: https://takeonme.org
title: Austin Hackers Academy

markdown: kramdown
highlighter: rouge
timezone: America/Chicago
homepage: index.html
meetingpage: meetings.html
aboutuspage: aboutus.html
mailinglistpage: mailinglist.html
ircpage: irc.html
ourspawnpage: ourspawn.html
rules: rules.html
chatpage: chat.html

avatar: /images/AHA-logo-black.png

footer-links:
  email: aha@takeonme.org
  github: AustinHackers/austinhackers.github.io
  twitter: austinhackers

include: [".well-known"]
include: ["cves"]
